package leetCode.Array;

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 */


import java.util.Arrays;
import java.util.Scanner;

public class FindTheDifference {

    public static void main(String[] args) {
        Scanner sc= new Scanner(System.in);

        System.out.print("String1: ");
        String s = sc.next();

        System.out.print("String2: ");
        String t = sc.next();

        System.out.println(findTheDifference(s,t));
    }

    public static char findTheDifference(String s, String t) {

        char[] s1 = s.toCharArray();
        Arrays.sort(s1);

        char[] t1 = t.toCharArray();
        Arrays.sort(t1);

        char diff = '1';

        for (int i = 0; i < s.length(); i++) {

            if(t1[i]!=s1[i]){
                diff = t1[i];
                return diff;
            }

        }

        return t1[t.length()-1];
    }

}
